// import Data from "/home/abdelmaoula/Documents/LP/Stage/pdf_ocr_app/backend/index.js"
import React , {useState , useEffect} from 'react'
function DataTest(){
    const [datasets, setDatasets] = useState("");
    useEffect(() => {
        // Using fetch to fetch the api from 
            // flask server it will be redirected to proxy
            try {
                fetch("http://localhost:5000/lois")
                .then(res =>res.json())
                .then(data=>setDatasets(data[0]))
            } catch (err) {
                console.log(err);
            }

        }, []);
        // console.log('datasets:',datasets)
        // console.log('datasets[0]:',datasets[0])
        return [datasets];
        // let data=[datasets[0]];
// [{   
//                 "loi": 'n° 60-18: relative à la Fondation des œuvres sociales \n des fonctionnaires de la direction générale\nde la protection civile',
//     'Article 1': "Il est créé, en vertu de la présente loi, une Institution\nà but non lucratif, dotée de la personnalité morale et de\nl'autonomie financière, dénommée « Fondation des œuvres\nsociales des fonctionnaires de la Direction générale de la\nprotection civile » ; désignée ci-après par « la Fondation ».\nLe siège de la Fondation est établit à Rabat.",
//     'Article 2': 'La Fondation a pour objet la création, la promotion\net la gestion des projets visant à réaliser des œuvres sociales\nau profit des fonctionnaires de la Direction générale de la\nprotection civile et des services extérieurs qui en relèvent ainsi\nqu’à leurs conjoints et leurs enfants.',
//     'Article 3': "Sont adhérents et peuvent bénéficier des services de\nla Fondation, sur le même pied d'égalité, conformément aux\nconditions fixées dans son règlement intérieur :\n— tous les fonctionnaires de la Direction générale de\nla protection civile et des services extérieurs qui en\nrelèvent ainsi que leurs conjoints et leurs enfants ;\n— les fonctionnaires de la Direction générale de la\nprotection civile qui sont en position de détachement\nauprès d’administrations, d'établissements ou autres\norganismes.\nBénéficient des services de la Fondation les retraités\nde la Direction générale de la protection civile ainsi que\nleurs conjoints, leurs enfants et aussi les ayants-droit des\nfonctionnaires et agents décédés en étant en fonction au sein\nde ladite Direction et des services extérieurs qui en relèvent.",
//     'Article 4': "La Fondation œuvre pour la réalisation des objectifs\nprévus à l’article 2 ci-dessus. A cet effet, elle est chargée\nconformément aux conditions fixées par son règlement\nintérieur, notamment, des missions suivantes :\n1- fournir des prestations et des services sociaux, de\nloisir et des centres d’estivage et des colonies de vacances et\norganiser des activités à caractère culturel et de loisir au profit\ndes adhérents, de leurs conjoints et de leurs enfants ;\n2- prendre les mesures nécessaires en partenariat\navec les organismes et les établissements spécialisés afin de\nfournir des services en matière de la couverture médicale et\nde l’assurance vie au profit des adhérents, de leurs conjoints\net de leurs enfants ;\n3- promouvoir ou assurer la réalisation des projets de\nlogements au profit des adhérents ;\n4- œuvrer afin de permettre aux adhérents et à\nleurs conjoints et enfants de bénéficier, à des conditions\npréférentielles, des services fournis par les établissements\npublics et privés en concluant des partenariats avec eux ;\n5- fournir d’autres services sociaux ou en faciliter l'accès\nau profit des adhérents, de leurs conjoints et de leurs enfants.",
//     'Article 5': "Seule la Fondation est habilitée, après autorisation de\nl'administration de créer, gérer ou exploiter toute structure à\ncaractère social en faveur des adhérents, de leurs conjoints,\nleurs enfants et ayant droits à l’intérieur des bâtiments relevant\nde la Direction générale de la protection civile.\nLa Fondation peut déléguer la gestion desdites\nstructures aux particuliers conformément aux conditions et\nrègles définies par son règlement intérieur ainsi que par un\ncahier des charges approuvé par le conseil d'orientation et de\ncontrôle prévue à l’article 6 ci-après.",
//     'Article 6': "Les organes de la Fondation sont :\n1. le conseil d'orientation et de contrôle ;\n2. le comité directeur ;\n3. les commissions régionales de suivi.\n11",
//     'Article 7': "Le conseil d'orientation et de contrôle se compose, outre\nle ministre de l’intérieur en tant que président et le directeur\ngénéral de la protection civile en tant que vice-président, de :\n— un (1) membre de chacune des directions centrales de\nla direction générale de la protection civile ainsi que de\nl'école nationale de la protection civile. Chacun de ces\nmembres est désigné parmi leurs responsables ou leurs\nfonctionnaires par arrêté de l'autorité gouvernementale\nchargée de l’intérieur pour une durée de cinq ans\nrenouvelable une seule fois ;\n— trois (3) membres représentant les fonctionnaires de la\nprotection civile travaillant à la Direction générale de\nla protection civile et ses services extérieurs, désignés\npar le conseil d'orientation et de contrôle et ce, pour une\ndurée de cinq ans renouvelable une seule fois.\nLorsqu'un membre du conseil d'orientation et de\ncontrôle perd la qualité en vertu de laquelle il a été nommé, il\nest procédé à son remplacement dans un délai ne dépassant\npas un mois à compter de la date de perte de ladite qualité et\nce, conformément aux modalités de nomination du membre\nremplacé et pour la durée de son mandat restant à courir.",
//     'Article 8': "Le conseil d'orientation et de contrôle est chargé de :\n— fixer une stratégie de travail de la Fondation, notamment\nles orientations générales et les options prioritaires pour\nl’accomplissement de ses missions ;\n— arrêter et évaluer périodiquement le plan d’action\nannuel et pluriannuel de la Fondation ;\n— élaborer le règlement intérieur de la Fondation et le\nsoumettre à l'approbation de l’autorité gouvernementale\nchargée de l’intérieur ;\n— fixer les conditions et les formes de passation des\nmarchés de travaux, de fournitures et de services pour\nle compte de la Fondation, conformément aux textes\nréglementaires en vigueur en la matière ;\n— approuver le budget annuel de la Fondation et les états\nde synthèse financiers de l’année budgétaire close ;\n— approuver les marchés de travaux, de fournitures et de\nservices dont le montant est supérieur à 1.000.000 de\ndirhams ;\n— approuver les conventions de coopération et de\npartenariat conclues avec les organismes publics et\nprivés ayant les mêmes objectifs ;\n— fixer le barème du montant des cotisations des adhérents\nde la Fondation dont le recouvrement est effectué par\nun prélèvement à la source par l’organisme chargé du\npaiement au profit de la Fondation ;\n— fixer les critères d'exonération des cotisations annuelles\npour les adhérents ayant un revenu limité ;\n— fixer le barème du montant des contributions qui sont à\nla charge des adhérents au titre des prestations fournies\npar la Fondation ;\n— établir un contrôle continue sur le fonctionnement de\nla Fondation et l’évaluer régulièrement ;\n— étudier et approuver le rapport annuel des activités de\nla Fondation que lui soumet le directeur du comité du\ndirecteur ;\n— prendre toutes les mesures jugées utiles pour la\npromotion et l'amélioration de la qualité des œuvres\nsociales gérées par la Fondation ;\n— statuer sur l'acceptation des dons et legs :\n— établir le statut du personnel de la Fondation.",
//     'Article 9': "Le conseil d'orientation et de contrôle peut, en tant que\nde besoin, créer tout comité spécialisé qu'il juge nécessaire,\naux fins d'accomplir les missions qui lui sont imparties en\nvertu du présent article.",
//     'Article 10': "Le conseil d'orientation et de contrôle se réunit sur\nconvocation de son président, en tant que de besoin et au\nmoins une fois chaque trois mois. Ses délibérations font l’objet\nde procès-verbaux signés par les membres présents.\nLe conseil délibère valablement lorsqu’au moins la\nmajorité absolue de ses membres sont présents. Si le quorum\nn’est pas atteint lors de la première réunion, le président\nappelle à une seconde réunion dans un délai ne dépassant pas\nquinze (15) jours. Dans ce cas, le conseil délibère valablement\nquel que soit le nombre des membres présents.",
//     'Article 11': 'Les fonctions des membres du conseil sont exercées, à\ntitre gratuit. Toutefois, des indemnités leur sont accordées,\nconformément au règlement intérieur de la Fondation, pour\ntoute mission ou déplacement effectué pour ses besoins.',
//     'Article 12': "Le comité directeur est composé, d’un directeur, d’un\ndirecteur adjoint, d’un secrétaire général, d’un secrétaire\ngénéral adjoint, d’un trésorier et d’un trésorier adjoint nommés\ntous par l'autorité gouvernementale chargée de l’intérieur.",
//     'Article 13': "Le comité directeur est chargé des missions suivantes :\n— préparer les travaux du conseil d'orientation et de\ncontrôle et appliquer ses décisions ;\n— assurer conformément aux directives du conseil\nd'orientation et de contrôle la promotion et le\ndéveloppement des œuvres d’assistance et d'entraide\nsusceptibles de promouvoir la situation familiale et\nsociale des fonctionnaires de la Direction générale de\nla protection civile et de ses services extérieurs, qu'ils\nsoient en service ou retraités ainsi que leurs ayants\ndroit ;\n\n 1169\n— assurer la direction et la gestion des œuvres visées au\nprécédent paragraphe ;\n— émettre son avis et présenter des propositions relatives\nà la direction et la gestion des œuvres sociales des\nfonctionnaires de la Direction générale de la protection\ncivile et de ses services.",
//     'Article 14': "Le directeur dirige la Fondation et agit en son nom,\nil assure la gestion de tous ses services et en coordonne les\nactivités. Il est également chargé de :\n— accomplir ou d’autoriser tous actes ou opérations\nrelatifs à l'objet de la Fondation ;\n— représenter la Fondation vis-à-vis de l'Etat, de toutes\nles administrations publiques ou privées, de tous tiers\net de faire tous actes conservatoires ;\n— assurer le recrutement du personnel de la Fondation\nconformément à son statut de personnel prévu à\nl’article 8 ci-dessus ;\n— représenter la Fondation devant la justice, d'engager\ntoutes actions judiciaires en vue d’en défendre les\nintérêts et d’en aviser immédiatement le président du\nconseil d'orientation et de contrôle.\nLe directeur est l’ordonnateur du budget de la Fondation.\nIl engage, à ce titre, les opérations prévues par le budget, les\nliquide et les ordonnance et assure la tenue de la compatibilité\ndes dépenses engagées.\nIl peut recevoir délégation du conseil d'orientation et\nde contrôle aux fins d'acquérir ou de céder des éléments du\npatrimoine foncier de la Fondation.\nIl peut également, déléguer une partie de ses pouvoirs au\ndirecteur adjoint qui l’assiste dans l'exercice de ses missions et\nle remplace en cas d'absence ou d’empêchement.",
//     'Article 15': "Le secrétaire général est chargé de la gestion administrative\ndela Fondation, notamment en ce quiconcerne les correspondances\net la tenue des archives.\nIl assiste aux réunions du conseil d'orientation et de\ncontrôle et du comité directeur et établit les procès-verbaux\nles concernant.\nIl établit le rapport moral du comité directeur et le\nprésente au conseil d'orientation et de contrôle.\nIl est assisté dans l’exercice de ses missions par le\nsecrétaire adjoint qui le remplace en cas d'absence ou\nd’empêchement.",
//     'Article 16': "Le trésorier est chargé de :\n— gérer les biens et les ressources de la Fondation. Il assure\nà ce titre, le recouvrement de ses recettes, la liquidation\ndes dépenses engagées par le directeur et la tenue de la\ncompatibilité de la Fondation ;\n— élaborer le projet du budget de la Fondation sous\nl'autorité du directeur ;\n— signer les chèques et les autres ordres de virement émis\nconjointement avec le directeur ou le directeur adjoint,\nle cas échéant ;\n— élaborer le rapport financier et le présenter au conseil\nd'orientation et de contrôle.\nIlest assisté dans l'exercice de ses missions par le trésorier\nadjoint qui le remplace en cas d’absence ou d'empêchement.",
//     'Article 17': "Il est créé, dans chacune des régions du Royaume, des\ncommissions régionales de suivi.\nElles sont chargées de suivre l'exécution des activités de\nla Fondation au niveau de leur ressort territorial.\nElles assurent également l'étude de tout projet ou\nprogramme qui leur est soumis par le conseil d'orientation\net de contrôle et proposent toutes les mesures susceptibles\nd’améliorer la qualité des services fournis par la Fondation.",
//     'Article 18': "Chaque commission régionale de suivi est composée\nd’un président, nommé par le conseil d'orientation et de\ncontrôle, de trois membres représentant l'Administration\nainsi que de trois membres représentant les fonctionnaires,\ndésignés également par le conseil d'orientation et de contrôle\nsur proposition du responsable régional de la protection civile\nconcerné.",
//     'Article 19': "Le budget de la Fondation comprend ce qui suit :\nEn recettes :\n— les subventions annuelles accordées par l'Etat et\ninscrites dans la loi des finances ;\n— les droits d’adhésion et les cotisations des membres\nadhérents ;\n—le produit des contributions financières des adhérents au\nfinancement de certaines prestations fournies au profit\nd'eux-mêmes et de leurs conjoints et enfants ;\n— les autres subventions provenant de toutes personnes\nde droit public ou privé :\n— les emprunts qui doivent être approuvés conformément\naux conditions prévues par les textes législatifs et\nréglementaires en vigueur, sauf si ils sont contractés\nauprès de l'Etat ou d’autres personnes de droit public ;\n— les dons et legs ;\n— les ressources diverses.\n1170 \n\nEn dépenses :\n— les dépenses de fonctionnement et d'investissement ;\n— les dépenses nécessaires à l'élaboration et la réalisation\ndes programmes et projets de la Fondation ;\n— la contribution à la prise en charge des frais des\nprestations fournies par la Fondation aux adhérents ;\n— toutes autres dépenses afférentes aux activités de la\nFondation.",
//     'Article 20': "Les comptes de la Fondation font, par appel à la\nconcurrence, l’objet d’un audit annuel mené, obligatoirement\nsous la responsabilité de commissaires aux comptes qui\nprocèdent à l'évaluation du régime de contrôle interne de\nla Fondation et s’assurent que ses états financiers donnent\nune image fidèle du patrimoine, de sa situation financière et\nses résultats. Ils transmettent le rapport d'audit au conseil\nd'orientation et de contrôle dans un délai n’excédant pas six\n(6) mois, après clôture de l’année budgétaire.",
//     'Article 21': "La Fondation est soumise au contrôle de l'administration\nterritoriale et l'inspection générale des finances et également\naux dispositions de la loi n° 62-99 relative au code des\njuridictions financières notamment ses articles 86 et 154.",
//     'Article 22': "La Fondation et ses ressources sont soumises au régime\nfiscal appliqué aux associations reconnues d'utilité publique.\nElle peut faire appel à la générosité publique sous réserve\nd’en faire la déclaration préalable au Secrétariat général du\ngouvernement.",
//     'Article 23': "Par dérogation aux dispositions législatives et\nréglementaires en vigueur, l'Administration peut mettre des\nfonctionnaires, à leur demande, à la disposition de la Fondation\net continuent d’être rémunérés par leurs administrations\nd’origine tout en conservant leurs droits à l'avancement et à\nla retraite.\nDes fonctionnaires peuvent être détachés à la Fondation\nconformément aux dispositions législatives et réglementaires\nen vigueur.",
//     'Article 24': "L'Etat, les collectivités territoriales et les autres\npersonnes de droit public peuvent mettre, gratuitement, à la\ndisposition de la Fondation les biens immeubles et meubles\nnécessaires pour l’accomplissement de ses missions et ce,\nconformément aux dispositions législatives et réglementaires\nen vigueur.\nLa Fondation peut, en outre posséder les biens meubles\net immeubles nécessaires à cette même fin.",
//     'Article 25': "Le règlement intérieur de la Fondation, visé à l’article 8\nde la présente loi, fixe les modalités d'organisation et de\ngestion de la Fondation et de ses organes, les attributions des\ncommissions régionales de suivi ainsi que les conditions et\nles modalités de bénéfice par les adhérents de chacune des\nprestations fournies par la Fondation.\nDans l'attente de l'approbation du règlement intérieur,\nun règlement provisoire est élaboré par une commission dont\nles membres sont désignés par l’autorité gouvernementale\nchargée de l’intérieur. Les premières réunions des organes de\nla Fondation se dérouleront alors sur la base dudit règlement.",
//     'Article 26': "Sont mis d'office à la disposition de la Fondation, à\ncompter de la date d'entrée en vigueur les biens immeubles\net meubles détenus par l'Etat et mis à la disposition de\nl'association des œuvres sociales des sapeurs-pompiers ainsi\nque tous les documents, contrats et archives y afférents.\nSont également transférés à titre gratuit et en toute\npropriété à la Fondation, à compter de la même date, les biens\nimmeubles et meubles et les actifs détenus par l'association des\nœuvres sociales des sapeurs-pompiers.",
//     'Article 27': "La Fondation est subrogée dans les droits et obligations\nde l’association des œuvres sociales des sapeurs-pompiers\npour l’ensemble des marchés de travaux, de fournitures et de\nservices ainsi que tous autres contrats et conventions conclus\npar ladite association avant l'entrée en vigueur de la présente\nloi.",
//     'Article 28': 'La présente loi entre en vigueur après sa publication au\nBulletin officiel.\n'
// }]
// return data;
}
export default DataTest;